### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by victorchall** [hafriedlander/stable-diffusion-grpcserver#17]
Just a heads up after running local in conda from environment.yaml, I'm getting missing modules/packages.  I started to pip install them. Here the order I encountered them: 

pyyaml
twisted
grpcio
hupper
wsgicors
protobuf
torch
service-identity
tqdm
diffusers
torchvision

I got to transformers and stopped, may be more.  Will pick up later if I have time.  Not entirely sure it will work because I don't know what versions of each it may require.  Let me know if I'm missing something here that will make this easier.

**Comment by hafriedlander** [comment]
Hi. The dependencies are all in pyproject.toml. I deliberately don't duplicate them in environment.yaml (it's why the install instructions all have `flit` as part of the process). It's a bit awkward, but this the more "python standards compliant" way of doing it.
