### ISSUE TITLE
getting inpainting and outpainting to work

### ISSUE THREAD

**Issue by imperator-maximus** [hafriedlander/stable-diffusion-grpcserver#3]
Hi, 
I am using same settings as for Stability AI grpc but Inpaiting and Outpainting (=both mode inpaint on server console) does not work at all.
It is obvious that this server uses inverted mask in comparison to Stability AI.
So I provided inverted version but it still does not work.
I played around with different strength parameters.
For transparent parts I provided grey fill because it is required in Stability AI. I tried it with transparent but it also does not work.
![image](https://user-images.githubusercontent.com/4406586/193413345-2f504a80-30e4-449d-abe4-ecc68c5206f4.png)
I have no problem to change anything but it would be nice to get an idea about how to do this?
Another question in this context: an option to generate alpha maskl from transparent parts on server would be also nice.
Thank you!

**Comment by hafriedlander** [comment]
I haven't tested the mask direction or strength versus grpc.stability.ai yet (unfortunately it's not documented in the proto).

The expectation for outpainting at the moment is: white for outside the image, black for inside the image, grey only for blending (and strictly inside the image - anything with no image data underneath must be pure black). I'll have to reverse-engineer what the official API uses.

**Comment by imperator-maximus** [comment]
I tried white and black:

![unknown_w](https://user-images.githubusercontent.com/4406586/193453333-f072ba0b-3e3e-4067-9590-9f79a5e8de8e.png)
![unknown](https://user-images.githubusercontent.com/4406586/193453335-8d8f6e7d-d09d-4378-a24c-6a5e20583ab6.png)

Results are even more worse now. But this is init img btw. For mask I already had black white.

**Comment by imperator-maximus** [comment]
here you get all informationen how Dreamstudio handles it: https://github.com/Stability-AI/stability-sdk/issues/62#issuecomment-1259834416
it is basically only if (png) scheduleParameters.setStart(mask ? 1 : 1 - this.$refs.editor.generationScheduleStart / 100);
for the strength plus images.
And with await editor.renderSVGToPNGDownload("image"); await editor.renderSVGToPNGDownload("mask");
you can save these images.

**Comment by imperator-maximus** [comment]
I am getting great results now with sampler=0 (should be DDIM )

**Comment by imperator-maximus** [comment]
I am closing this now because it seems to work and might open new tickets on detail problems. Thank you! :)
