### ISSUE TITLE
Seamless outpainting not working

### ISSUE THREAD

**Issue by lkwq007** [hafriedlander/stable-diffusion-grpcserver#8]
Hi, I just tried the `UnifiedPipeline` (at https://github.com/hafriedlander/stable-diffusion-grpcserver/commit/8751040e0ad283060b54da1c6a0aa03633517073) on stable-diffusion v1.4 with `strength=1.0`, `step=50`, `guidance_scale=7.5`, using DDIM scheduler with `eta=0`. The size of `init_image` is 512x512. 
I found that it cannot generate coherent outputs in this setting. 
I was wondering if I configured it correctly. Thanks. 

Below are some example outputs (for each input, I have tried about 10 times, and all outputs are inconsistent with the exiting regions)

Prompt: "sky", outpainted right part
![outpaint_20221006_173554](https://user-images.githubusercontent.com/1665437/194281328-aaaddad8-077c-4a8f-aaef-217e0b6d2cb4.png)

Prompt: "a girl, oil painting ", outpainted bottom-left corner
![outpaint_20221006_174254](https://user-images.githubusercontent.com/1665437/194281370-ec2d3ca1-9846-440f-aa6f-aed01486bd1c.png)

**Comment by hafriedlander** [comment]
Hi. Are you passing in a mask? Mask preparation is critical to good results (and currently not well documented, sorry).

There is some mask manipulation available in the server, so for now the best recommendation for outpaint is:

- Pass in a mask with only pure white (for areas where there are no good pixels) and pure black (for areas where there are good pixels). It can be an RGB or single-channel image.

- Use an image adjustment property on the mask like this:

```
ImageAdjustment(
  blur: ImageAdjustment_Gaussian(
    sigma: 32,
    direction: GaussianDirection.DIRECTION_UP
  )
)
```

There are extra adjustments in case you want to use a mask from an Alpha channel (by remapping it into the Red channel), to crop, or to do other adjustments.

**Comment by lkwq007** [comment]
Thank you for your information. It works much better with processed masks. 

> Pass in a mask with only pure white and pure black 

I had used masks in this way. It seems that non-smooth boundaries of the mask tends to result in seams or incoherent results.
